language: php
php:
  - 5.6
sudo: false
before_script:
  - phpenv config-rm xdebug.ini
  - cd 
  - composer install --dev --no-interaction --prefer-source
  - ulimit -c
  - ulimit -c unlimited -S
  - /home/travis/.phpenv/versions/5.6/bin/composer self-update
  - composer self-update
  - cp .env.travis .env
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - mysql -e 'create database IF NOT EXISTS  cineacademy;'   -uroot
  - mysql -uroot cineacademy < mysql/cineacademy.sql
  - php artisan  db:seed --force
script: phpunit
cache:
  directories:
    - $HOME/.composer/cache
notifications:
  email:
    - julien@meetserious.com
services:
  - mysql
